[package]
name             = "core-highlight"
edition.workspace    = true
version.workspace    = true
license-file.workspace    = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
thiserror = { workspace = true }
regex     = { workspace = true }
serde     = { workspace = true }
